# Generated by Django 5.1 on 2026-01-31 13:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompetencyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(default='layers', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CompetencyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('color', models.CharField(default='text-gray-600', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(default='multiple_choice', max_length=50)),
                ('points', models.PositiveIntegerField(default=10)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app2.competency')),
            ],
        ),
        migrations.AddField(
            model_name='competency',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='app2.competencycategory'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('instructor_name', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=20)),
                ('duration', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('introduction', models.TextField()),
                ('tags', models.JSONField(default=list)),
                ('questions', models.PositiveIntegerField(default=0)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='course_photos/')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=False)),
                ('department', models.CharField(blank=True, default='General', help_text='The department this course belongs to (e.g., IT, Sales, HR)', max_length=100)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='CourseStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.PositiveIntegerField(default=0)),
                ('completion', models.PositiveIntegerField(default=0)),
                ('enrolled', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('duration', models.CharField(max_length=50)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='app2.course')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='app2.course')),
                ('employees', models.ManyToManyField(blank=True, limit_choices_to={'lms_profile__userType': 'employee'}, related_name='member_of_groups', to=settings.AUTH_USER_MODEL)),
                ('team_leaders', models.ManyToManyField(blank=True, limit_choices_to={'lms_profile__userType': 'team-leader'}, related_name='led_groups', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompetencyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('financial_year', models.CharField(default='FY 2024-25', max_length=20)),
                ('hq', models.CharField(blank=True, max_length=100, null=True)),
                ('business_unit', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('section', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app2.group')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app2.group')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=20)),
                ('completed', models.BooleanField(default=False)),
                ('sample', models.BooleanField(default=False)),
                ('content', models.TextField()),
                ('video', models.FileField(blank=True, null=True, upload_to='lesson_videos/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap', to='app2.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LessonAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='lesson_materials/')),
                ('url_link', models.URLField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='app2.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='LMSProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('userType', models.CharField(choices=[('admin', 'Admin'), ('team-leader', 'Team Leader'), ('employee', 'Employee')], default='Employee', max_length=30)),
                ('designation', models.CharField(blank=True, default='Employee', max_length=100, null=True)),
                ('department', models.CharField(blank=True, default='General', max_length=100, null=True)),
                ('hq', models.CharField(blank=True, default='hq', max_length=100, null=True)),
                ('bu', models.CharField(blank=True, default='bu', max_length=100, null=True)),
                ('section', models.CharField(blank=True, default='section', max_length=100, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('companyName', models.CharField(blank=True, max_length=100, null=True)),
                ('profileImage', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lms_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Urgent')], default='info', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lms_notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lms_sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('org_type', models.CharField(choices=[('hq', 'Headquarters'), ('bu', 'Business Units'), ('dept', 'Departments'), ('section', 'Sections'), ('designation', 'Designations')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app2.organizationnode')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='app2.question')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('test_type', models.CharField(choices=[('pre', 'Pre Test'), ('post', 'Post Test')], default='pre', help_text='Type of test: Pre-test (before course) or Post-test (after course)', max_length=10)),
                ('order', models.PositiveIntegerField(default=0, help_text='Determines position in the course content list.')),
                ('passing_criteria', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_time', models.PositiveIntegerField(default=30, help_text='Time limit in minutes')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='app2.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app2.test'),
        ),
        migrations.CreateModel(
            name='PostTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('score', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('percentage', models.FloatField(default=0.0)),
                ('passed', models.BooleanField(default=False)),
                ('answers_snapshot', models.JSONField(default=dict)),
                ('time_taken', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_test_results', to='app2.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_test_results', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post_test_results', to='app2.test')),
            ],
            options={
                'verbose_name': 'Post Test Result',
                'verbose_name_plural': 'Post Test Results',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='AnswerSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=dict)),
                ('score', models.IntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='app2.test')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('topic', models.CharField(max_length=255)),
                ('trainer_name_text', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Planned', 'Planned'), ('Actual', 'Actual'), ('Cancelled', 'Cancelled')], default='Planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='app2.group')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='CourseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('is_pretest_completed', models.BooleanField(default=False)),
                ('assigned_level', models.CharField(blank=True, max_length=20, null=True)),
                ('is_course_completed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_status', models.CharField(choices=[('pending_pretest', 'Pending Pre-test'), ('in_progress', 'Learning'), ('ready_for_posttest', 'Ready for Post-test'), ('completed', 'Completed'), ('failed_retaking', 'Failed - Retaking')], default='pending_pretest', max_length=30)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_created', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='app2.course')),
                ('employee', models.ForeignKey(limit_choices_to={'lms_profile__userType__in': ['employee', 'team-leader']}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_at'],
                'unique_together': {('employee', 'course')},
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_requests', to='app2.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeCompetencyMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_level', models.PositiveIntegerField(default=1)),
                ('target_level', models.PositiveIntegerField(default=3)),
                ('source', models.CharField(default='Manual', max_length=50)),
                ('assessed_at', models.DateTimeField(auto_now=True)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.competency')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_matrix', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('employee', 'competency')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeGrowthReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_test_date', models.DateTimeField(blank=True, null=True)),
                ('pre_test_score', models.IntegerField(blank=True, null=True)),
                ('pre_test_total', models.IntegerField(blank=True, null=True)),
                ('pre_test_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('post_test_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('score_improvement', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('growth_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('growth_status', models.CharField(blank=True, max_length=50, null=True)),
                ('growth_status_display', models.CharField(blank=True, max_length=50, null=True)),
                ('initial_level', models.CharField(blank=True, max_length=100, null=True)),
                ('final_passed', models.BooleanField(default=False)),
                ('total_attempts', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeegrowthreport_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.course')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='app2.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'course', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='RuleCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_level', models.PositiveIntegerField(default=3)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.competency')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_competencies', to='app2.competencyrule')),
            ],
            options={
                'unique_together': {('rule', 'competency')},
            },
        ),
        migrations.CreateModel(
            name='PreTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('percentage', models.FloatField(default=0.0)),
                ('assigned_level', models.CharField(default='Beginner', max_length=20)),
                ('time_taken', models.PositiveIntegerField(default=0, help_text='Time in seconds')),
                ('answers_snapshot', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_test_results', to='app2.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_test_results', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pre_test_results', to='app2.test')),
            ],
            options={
                'verbose_name': 'Pre-Test Result',
                'verbose_name_plural': 'Pre-Test Results',
                'ordering': ['-completed_at'],
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='TestProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.course')),
                ('submission', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app2.answersubmission')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Test Progress',
                'verbose_name_plural': 'Test Progress',
                'unique_together': {('user', 'test')},
            },
        ),
    ]
