# Generated by Django 5.1 on 2026-02-02 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetencyAssessmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField()),
                ('score', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=100)),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('assessed_by', models.CharField(default='System', max_length=150)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.competency')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assessed_at'],
            },
        ),
    ]
