# Generated by Django 5.2.8 on 2026-07-02 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_alter_course_description_alter_course_introduction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseassignment',
            name='employee',
            field=models.ForeignKey(limit_choices_to=models.Q(('role__permissions__codename__in', ['view_courses', 'create_courses', 'update_courses']), models.Q(('role__permissions__codename', 'manage_courses'), _negated=True)), on_delete=django.db.models.deletion.CASCADE, related_name='assigned_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='employees',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('role__permissions__codename', 'view_courses'), models.Q(('role__permissions__codename', 'manage_courses'), _negated=True)), related_name='member_of_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='team_leaders',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('role__permissions__codename__in', ['create_groups', 'update_groups', 'manage_groups'])), related_name='led_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
