# Generated by Django 5.2.8 on 2026-07-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_alter_lessonattachment_url_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lmsprofile',
            name='userType',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
