# Generated by Django 5.2.5 on 2025-09-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0070_remove_multiskilling_hierarchy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillMatrixFeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(choices=[('ojt_evaluation', 'OJT + Evaluation'), ('cycle_evaluation', '10 Cycle + Evaluation'), ('quantity_ojt_evaluation', 'Quantity OJT + Evaluation')], max_length=100, unique=True)),
                ('enabled', models.BooleanField(default=False)),
            ],
        ),
    ]
