# Generated by Django 5.2.5 on 2025-09-29 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0071_skillmatrixfeatureflag'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_level_required', models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], max_length=20, null=True)),
                ('minimum_operators', models.PositiveIntegerField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='station_managers_as_department', to='app1.hierarchystructure')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='station_managers_as_station', to='app1.hierarchystructure')),
            ],
            options={
                'db_table': 'station_manager',
            },
        ),
    ]
