# Generated by Django 5.1 on 2025-10-06 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0072_stationmanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTQandPDIdepartment',
            fields=[
                ('CtqPdi_id', models.AutoField(primary_key=True, serialize=False)),
                ('CtqPdi_name', models.CharField(max_length=100)),
                ('factory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctq_pdi_departments', to='app1.factory')),
            ],
            options={
                'db_table': 'CtqPdi',
                'unique_together': {('CtqPdi_name', 'factory')},
            },
        ),
        migrations.CreateModel(
            name='ManagementReviewCTQandPDI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('CTQ', 'CTQ'), ('PDI', 'PDI'), ('OTHER', 'Other'), ('MARU A', 'Maru A'), ('CRITICAL', 'Critical')], max_length=10)),
                ('month_year', models.DateField()),
                ('new_operators_joined', models.IntegerField()),
                ('new_operators_trained', models.IntegerField()),
                ('defects_msil', models.IntegerField()),
                ('defects_tier1', models.IntegerField()),
                ('internal_rejection', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.department')),
            ],
            options={
                'unique_together': {('department', 'month_year', 'review_type')},
            },
        ),
    ]
