# Generated by Django 5.1 on 2025-10-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0073_ctqandpdidepartment_managementreviewctqandpdi'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementreviewctqandpdi',
            name='training_actual',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managementreviewctqandpdi',
            name='training_plan',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
