# Generated by Django 5.1 on 2025-10-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0074_managementreviewctqandpdi_training_actual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementreviewctqandpdi',
            name='review_type',
            field=models.CharField(choices=[('CTQ', 'CTQ'), ('PDI', 'PDI'), ('OTHER', 'Other'), ('MARU A', 'Maru A'), ('CRITICAL', 'Critical'), ('TOTAL', 'Total (Auto-Aggregated)')], max_length=10),
        ),
    ]
