# Generated by Django 5.2.5 on 2025-10-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('app1', '0072_stationmanager'),
        ('app1', '0075_alter_managementreviewctqandpdi_review_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BioUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeid', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
    ]
