# Generated by Django 5.2.1 on 2025-10-14 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0083_rename_station_id_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traineeinfo',
            name='station_id',
        ),
        migrations.AlterField(
            model_name='traineeinfo',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainees', to='app1.station'),
        ),
    ]
