# Generated by Django 5.2.1 on 2025-10-09 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0079_traineeinfo_station_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ojtlevel2quantity',
            name='station',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='ojt_quantity_records', to='app1.station'),
        ),
        migrations.AlterField(
            model_name='ojtlevel2quantity',
            name='trainee_id',
            field=models.CharField(max_length=50),
        ),
    ]
