# Generated by Django 5.2.1 on 2025-10-13 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0080_ojtlevel2quantity_station_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ojtlevel2quantity',
            name='station_name',
        ),
        migrations.RemoveField(
            model_name='traineeinfo',
            name='station_id',
        ),
        migrations.AlterField(
            model_name='ojtlevel2quantity',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quantity_trainees', to='app1.station'),
        ),
        migrations.AlterField(
            model_name='ojtlevel2quantity',
            name='trainee_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='traineeinfo',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainees', to='app1.station'),
        ),
    ]
