# Generated by Django 5.2.1 on 2025-10-13 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0081_remove_ojtlevel2quantity_station_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ojtlevel2quantity',
            name='station_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traineeinfo',
            name='station_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainees', to='app1.station'),
        ),
        migrations.AlterField(
            model_name='ojtlevel2quantity',
            name='station',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='ojt_quantity_records', to='app1.station'),
        ),
        migrations.AlterField(
            model_name='ojtlevel2quantity',
            name='trainee_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='traineeinfo',
            name='station',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
