# # Generated by Django 5.2.1 on 2025-10-13 09:00

# from django.db import migrations


# class Migration(migrations.Migration):

#     dependencies = [
#         ('app1', '0076_ojtlevel2quantity_station_name_and_more'),
#     ]

#     operations = [
#     ]
from django.db import migrations

def rename_station_id_id(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    schema_editor.execute(
        'ALTER TABLE app1_traineeinfo RENAME COLUMN station_id_id TO station_id'
    )

class Migration(migrations.Migration):
    dependencies = [
        ('app1', '0082_ojtlevel2quantity_station_name_and_more'),  # Latest migration
    ]
    operations = [
        migrations.RunPython(rename_station_id_id, reverse_code=migrations.RunPython.noop),
    ]