# Generated by Django 5.1 on 2025-10-16 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0077_biometricattendance'),
        ('app1', '0078_remove_traineeinfo_station_id_and_more'),
    ]

    operations = [
    ]
