# Generated by Django 5.1 on 2025-10-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0084_merge_20251016_1036"),
    ]

    operations = [
        migrations.CreateModel(
            name="StationSheetConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level_id", models.IntegerField(blank=True, null=True)),
                ("department_id", models.IntegerField(blank=True, null=True)),
                ("line_id", models.IntegerField(blank=True, null=True)),
                ("subline_id", models.IntegerField(blank=True, null=True)),
                ("station_id", models.IntegerField()),
                ("ojt_enabled", models.BooleanField(default=False)),
                ("ten_cycle_enabled", models.BooleanField(default=False)),
                ("skill_evaluation_enabled", models.BooleanField(default=False)),
                ("others_enabled", models.BooleanField(default=False)),
                ("evaluation_enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=[
                            "level_id",
                            "department_id",
                            "line_id",
                            "subline_id",
                            "station_id",
                        ],
                        name="station_config_idx",
                    )
                ],
                "unique_together": {
                    ("level_id", "department_id", "line_id", "subline_id", "station_id")
                },
            },
        ),
    ]
