# Generated by Django 5.2.5 on 2025-10-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('app1', '0084_merge_20251016_1036'),
        ('app1', '0085_stationsheetconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='raw_answers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
