# Generated by Django 5.2.1 on 2025-11-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0086_score_raw_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatequestion',
            name='option_a_image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/'),
        ),
        migrations.AddField(
            model_name='templatequestion',
            name='option_b_image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/'),
        ),
        migrations.AddField(
            model_name='templatequestion',
            name='option_c_image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/'),
        ),
        migrations.AddField(
            model_name='templatequestion',
            name='option_d_image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/'),
        ),
        migrations.AddField(
            model_name='templatequestion',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/'),
        ),
    ]
