# Generated by Django 5.2.1 on 2025-11-13 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0087_templatequestion_option_a_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastertable',
            name='current_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_on_line', to='app1.line'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='current_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_at_station', to='app1.station'),
        ),
    ]
