# Generated by Django 5.2.1 on 2025-11-13 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0088_mastertable_current_line_mastertable_current_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='handoversheet',
            name='allocated_line',
            field=models.ForeignKey(blank=True, help_text='The specific line within the department the employee was allocated to during this handover.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.line'),
        ),
        migrations.AddField(
            model_name='handoversheet',
            name='allocated_station',
            field=models.ForeignKey(blank=True, help_text='The specific station the employee was allocated to during this handover.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.station'),
        ),
    ]
