# Generated by Django 5.2.1 on 2025-11-13 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0089_handoversheet_allocated_line_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traineeinfo',
            options={'verbose_name': 'Trainee Info', 'verbose_name_plural': 'Trainee Info'},
        ),
        migrations.AddField(
            model_name='traineeinfo',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trainees', to='app1.level'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='traineeinfo',
            unique_together={('emp_id', 'station', 'level')},
        ),
    ]
