# Generated by Django 5.2.1 on 2025-11-13 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0090_alter_traineeinfo_options_traineeinfo_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ojtlevel2quantity',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ojt_quantity_records', to='app1.department'),
        ),
        migrations.AlterUniqueTogether(
            name='ojtlevel2quantity',
            unique_together={('trainee_id', 'level', 'station', 'department')},
        ),
    ]
