# Generated by Django 5.2.1 on 2025-11-14 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0091_ojtlevel2quantity_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelDayRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_days', models.PositiveSmallIntegerField(help_text='Number of days needed to complete OJT')),
                ('level', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='day_requirement', to='app1.level')),
            ],
        ),
    ]
