# Generated by Django 5.1 on 2025-11-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0093_question_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurrenceInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_months', models.IntegerField(help_text='Recurrence interval in months (e.g., 3 for quarterly, 6 for semi-annually)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recurrence Interval',
                'verbose_name_plural': 'Recurrence Intervals',
            },
        ),
    ]
