# Generated by Django 5.1 on 2025-11-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0094_recurrenceinterval'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='employee_Id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
