# Generated by Django 5.1 on 2025-11-18 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0096_alter_userregistration_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecurrenceInterval',
        ),
    ]
