# Generated by Django 5.2.1 on 2025-11-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0097_delete_recurrenceinterval'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='option_image',
            field=models.ImageField(blank=True, null=True, upload_to='options/'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/'),
        ),
        migrations.AlterField(
            model_name='option',
            name='option_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
