# Generated by Django 5.1 on 2025-11-18 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0098_option_option_image_question_question_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurrenceInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_months', models.IntegerField(help_text='Interval in months for automatic rescheduling (e.g., 3 or 6)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='Whether this schedule should automatically recur'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='last_recurrence_date',
            field=models.DateField(blank=True, help_text='Date when the last recurrence was created', null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='parent_schedule',
            field=models.ForeignKey(blank=True, help_text='Original schedule if this is a recurring instance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_schedules', to='app1.schedule'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='recurrence_interval',
            field=models.ForeignKey(blank=True, help_text='Recurrence interval for this schedule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='app1.recurrenceinterval'),
        ),
    ]
