# Generated by Django 5.1 on 2025-11-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0099_recurrenceinterval_schedule_is_recurring_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
