# Generated by Django 5.1 on 2025-11-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0100_userregistration_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humanbodychecksheet',
            name='answer',
            field=models.CharField(choices=[('eligible', 'Eligible'), ('not_eligible', 'Not Eligible'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
