# Generated by Django 5.1 on 2025-11-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0101_alter_humanbodychecksheet_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='last_recurrence_date',
        ),
        migrations.AddField(
            model_name='schedule',
            name='completed_date',
            field=models.DateField(blank=True, help_text='Date when training was marked as completed', null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='recurring_schedule_created',
            field=models.BooleanField(default=False, help_text='Flag to track if recurring schedule has been created'),
        ),
    ]
