# Generated by Django 5.1 on 2025-11-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0104_alter_advancemanpowerdashboard_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='humanbodyquestions',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='humanbodyquestions',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
