# Generated by Django 5.1 on 2025-11-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0105_alter_humanbodyquestions_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='emergency_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
