# Generated by Django 5.2.1 on 2025-11-21 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0106_userregistration_emergency_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingbatch',
            name='batch_id',
            field=models.CharField(help_text='e.g., BATCH-20251121-42', max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
