# Generated by Django 5.2.1 on 2025-11-21 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0107_alter_trainingbatch_batch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingbatch',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
