# Generated by Django 5.2.1 on 2025-11-21 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0108_alter_trainingbatch_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingbatch',
            name='batch_id',
            field=models.CharField(help_text='e.g., BATCH-070824', max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='trainingbatch',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Active batches appear in the attendance dropdown.'),
        ),
    ]
