# Generated by Django 5.2.1 on 2025-11-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0109_alter_trainingbatch_batch_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingbatch',
            name='batch_id',
            field=models.CharField(help_text='e.g., BATCH-21-11-2025-1', max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
