# Generated by Django 5.1 on 2025-11-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0111_rescheduledsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='humanbodychecksession',
            name='remarks',
            field=models.TextField(blank=True, help_text='Remarks regarding the session or modification reason', null=True),
        ),
    ]
