# Generated by Django 5.2.1 on 2025-11-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0112_humanbodychecksession_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='rescheduledsession',
            name='attendance_photo',
            field=models.ImageField(blank=True, help_text='Photo taken when marking attendance for rescheduled session', null=True, upload_to='rescheduled_attendance_photos/'),
        ),
    ]


