# Generated by Django 5.1 on 2025-11-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0113_rescheduledsession_attendance_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='line',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subline',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
