# Generated by Django 5.1 on 2025-11-27 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0114_user_line_user_subline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handoversheet',
            name='contractor_name',
        ),
        migrations.RemoveField(
            model_name='handoversheet',
            name='industrial_experience',
        ),
        migrations.RemoveField(
            model_name='handoversheet',
            name='kpapl_experience',
        ),
        migrations.RemoveField(
            model_name='handoversheet',
            name='p_and_a_name',
        ),
        migrations.RemoveField(
            model_name='handoversheet',
            name='qa_hod_name',
        ),
        migrations.AddField(
            model_name='handoversheet',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='The System User (Supervisor/Manager) to whom this employee is assigned.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_handovers', to=settings.AUTH_USER_MODEL),
        ),
    ]
