# Generated by Django 5.1 on 2025-11-27 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0115_remove_handoversheet_contractor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='handoversheet',
            name='allocated_subline',
            field=models.ForeignKey(blank=True, help_text='The specific subline within the department the employee was allocated to during this handover.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.subline'),
        ),
    ]
