# Generated by Django 5.1 on 2025-11-24 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0117_handovernotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='RescheduleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_date', models.DateField()),
                ('original_time', models.TimeField()),
                ('original_venue', models.CharField(blank=True, max_length=200, null=True)),
                ('original_trainer', models.CharField(blank=True, max_length=200, null=True)),
                ('original_status', models.CharField(choices=[('absent', 'Absent'), ('rescheduled', 'Rescheduled')], help_text='Original attendance status (absent or rescheduled)', max_length=20)),
                ('rescheduled_date', models.DateField()),
                ('rescheduled_time', models.TimeField()),
                ('reschedule_reason', models.TextField()),
                ('final_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('pending', 'Pending')], default='pending', help_text='Final attendance status after reschedule', max_length=20)),
                ('final_attendance_marked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_history', to='app1.mastertable')),
                ('original_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_histories', to='app1.schedule')),
            ],
            options={
                'verbose_name_plural': 'Reschedule Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
