# Generated by Django 5.1 on 2025-11-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0118_reschedulehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='recurrence_interval',
        ),
        migrations.AddField(
            model_name='schedule',
            name='next_training_date_override',
            field=models.DateField(blank=True, help_text='Manually set next training date (overrides calculated date)', null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='recurrence_months',
            field=models.IntegerField(blank=True, help_text='Number of months for recurrence (1-10). Null means no recurrence.', null=True),
        ),
        migrations.DeleteModel(
            name='RecurrenceInterval',
        ),
    ]
