# Generated by Django 5.2.1 on 2025-12-02 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0119_remove_schedule_recurrence_interval_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leveldayrequirement',
            options={'ordering': ['level__level_id']},
        ),
    ]
