# Generated by Django 5.2.1 on 2025-12-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0121_evaluationcriterion_evaluationlevel2_evaluationscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationsheetconfig',
            name='maru_a_enabled',
            field=models.BooleanField(default=False),
        ),
    ]



