# Generated by Django 5.2.1 on 2025-12-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0122_stationsheetconfig_maru_a_enabled'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stationsheetconfig',
            new_name='cfg_full',
            old_name='station_config_idx',
        ),
        migrations.AlterUniqueTogether(
            name='stationsheetconfig',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='stationsheetconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stationsheetconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='stationsheetconfig',
            index=models.Index(fields=['level_id', 'station_id'], name='cfg_level_station'),
        ),
        migrations.AddIndex(
            model_name='stationsheetconfig',
            index=models.Index(fields=['level_id', 'department_id', 'station_id'], name='cfg_dept'),
        ),
        migrations.AddIndex(
            model_name='stationsheetconfig',
            index=models.Index(fields=['level_id', 'department_id', 'line_id', 'station_id'], name='cfg_line'),
        ),
    ]
