# Generated by Django 5.2.1 on 2025-12-05 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0123_rename_station_config_idx_cfg_full_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stationsheetconfig',
            name='cfg_full',
        ),
        migrations.RemoveIndex(
            model_name='stationsheetconfig',
            name='cfg_level_station',
        ),
        migrations.RemoveIndex(
            model_name='stationsheetconfig',
            name='cfg_dept',
        ),
        migrations.RemoveIndex(
            model_name='stationsheetconfig',
            name='cfg_line',
        ),
    ]
