# Generated by Django 5.2.1 on 2025-12-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0124_remove_stationsheetconfig_cfg_full_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationsheetconfig',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stationsheetconfig',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='stationsheetconfig',
            unique_together={('level_id', 'department_id', 'line_id', 'subline_id', 'station_id')},
        ),
        migrations.AddIndex(
            model_name='stationsheetconfig',
            index=models.Index(fields=['level_id', 'department_id', 'line_id', 'subline_id', 'station_id'], name='station_config_idx'),
        ),
    ]
