# Generated by Django 5.2.1 on 2025-12-08 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0125_alter_stationsheetconfig_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'station_type',
            },
        ),
        migrations.AlterField(
            model_name='hierarchystructure',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='app1.department'),
        ),
        migrations.AlterField(
            model_name='hierarchystructure',
            name='factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='app1.factory'),
        ),
        migrations.AlterField(
            model_name='hierarchystructure',
            name='hq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='app1.hq'),
        ),
        migrations.AlterField(
            model_name='hierarchystructure',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='app1.line'),
        ),
        migrations.AlterField(
            model_name='hierarchystructure',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='app1.station'),
        ),
        migrations.AlterField(
            model_name='hierarchystructure',
            name='subline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='app1.subline'),
        ),
        migrations.AddField(
            model_name='hierarchystructure',
            name='station_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.stationtype'),
        ),
    ]
