# Generated by Django 5.2.1 on 2025-12-09 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0126_stationtype_alter_hierarchystructure_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hierarchystructure',
            name='station_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
