# Generated by Django 5.2.1 on 2025-12-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0127_alter_hierarchystructure_station_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationtype',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='station_icons/'),
        ),
    ]
