# Generated by Django 5.2.1 on 2025-12-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0128_stationtype_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationtype',
            name='color',
            field=models.CharField(default='from-blue-600 to-blue-700', help_text='Tailwind gradient class, e.g. from-red-600 to-red-700', max_length=50),
        ),
    ]
