# Generated by Django 5.1 on 2025-12-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0129_stationtype_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('employee_registration', 'Employee Registration'), ('level_exam_completed', 'Level Exam Completed'), ('training_added', 'Training Added'), ('training_updated', 'Training Updated'), ('training_scheduled', 'Training Scheduled'), ('training_completed', 'Training Completed'), ('training_reschedule', 'Training Reschedule'), ('refresher_training_scheduled', 'Refresher Training Scheduled'), ('refresher_training_completed', 'Refresher Training Completed'), ('hanchou_exam_completed', 'Hanchou Exam Completed'), ('shokuchou_exam_completed', 'Shokuchou Exam Completed'), ('ten_cycle_evaluation_completed', '10 Cycle Evaluation Completed'), ('ojt_completed', 'OJT Completed'), ('ojt_quantity_completed', 'OJT Quantity Completed'), ('machine_allocated', 'Machine Allocated'), ('test_assigned', 'Test Assigned'), ('evaluation_completed', 'Evaluation Completed'), ('retraining_scheduled', 'Retraining Scheduled'), ('retraining_completed', 'Retraining Completed'), ('human_body_check_completed', 'Human Body Check Completed'), ('milestone_reached', 'Milestone Reached'), ('system_alert', 'System Alert'), ('multiskilling_scheduled', 'Multiskilling Scheduled'), ('multiskilling_completed', 'Multiskilling Completed'), ('skill_matrix_updated', 'Skill Matrix Updated')], max_length=50),
        ),
    ]
