# Generated by Django 5.2.8 on 2025-12-02 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('app1', '0125_alter_stationsheetconfig_created_at_and_more'),
        ('app1', '0130_alter_notification_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefresherQuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passing_score', models.PositiveSmallIntegerField(default=70, help_text='Percentage required to pass')),
                ('time_limit_minutes', models.PositiveSmallIntegerField(default=30, help_text='Time for Pre & Post Test')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refresher_question_bank', to='app1.curriculum')),
            ],
            options={
                'verbose_name': 'Refresher Question Bank',
                'verbose_name_plural': 'Refresher Question Banks',
            },
        ),
        migrations.CreateModel(
            name='RefresherQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='refresher/questions/')),
                ('option_a', models.CharField(max_length=500)),
                ('option_b', models.CharField(max_length=500)),
                ('option_c', models.CharField(blank=True, max_length=500)),
                ('option_d', models.CharField(blank=True, max_length=500)),
                ('option_a_image', models.ImageField(blank=True, null=True, upload_to='refresher/options/')),
                ('option_b_image', models.ImageField(blank=True, null=True, upload_to='refresher/options/')),
                ('option_c_image', models.ImageField(blank=True, null=True, upload_to='refresher/options/')),
                ('option_d_image', models.ImageField(blank=True, null=True, upload_to='refresher/options/')),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], help_text='Correct option', max_length=1)),
                ('marks', models.PositiveSmallIntegerField(default=1)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app1.refresherquestionbank')),
            ],
            options={
                'verbose_name': 'Refresher Question',
                'verbose_name_plural': 'Refresher Questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RefresherTestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('pre', 'Pre-Test'), ('post', 'Post-Test')], max_length=10)),
                ('mode', models.CharField(choices=[('remote', 'Remote Control'), ('individual', 'Individual (PC/Tablet)')], default='individual', max_length=10)),
                ('remote_key_id', models.CharField(blank=True, max_length=20, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_questions', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresher_tests', to='app1.mastertable')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresher_test_sessions', to='app1.schedule')),
            ],
            options={
                'verbose_name': 'Refresher Test Session',
                'verbose_name_plural': 'Refresher Test Sessions',
                'unique_together': {('schedule', 'employee', 'test_type')},
            },
        ),
        migrations.CreateModel(
            name='RefresherAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('is_correct', models.BooleanField()),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.refresherquestion')),
                ('test_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='app1.refreshertestsession')),
            ],
            options={
                'unique_together': {('test_session', 'question')},
            },
        ),
    ]
