# Generated by Django 5.2.8 on 2025-12-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0131_refresherquestionbank_refresherquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refresherquestion',
            name='is_active',
            field=models.BooleanField(default=True, help_text="If False, this question won't appear in new tests"),
        ),
        migrations.AlterField(
            model_name='refresherquestion',
            name='option_a',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='refresherquestion',
            name='option_b',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='refresherquestion',
            name='question_text',
            field=models.TextField(blank=True),
        ),
    ]
