# Generated by Django 5.2.8 on 2025-12-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0132_refresherquestion_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='training_stage',
            field=models.IntegerField(default=0, help_text='Current stage of the training flow'),
        ),
    ]
