# Generated by Django 5.2.8 on 2025-12-05 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0133_schedule_training_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refresherquestionbank',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='training_name',
        ),
        migrations.AddField(
            model_name='refresherquestionbank',
            name='category',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='refresher_question_bank', to='app1.training_category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='topics',
            field=models.ManyToManyField(related_name='scheduled_sessions', to='app1.curriculum'),
        ),
    ]
