# Generated by Django 5.1 on 2025-12-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0134_remove_refresherquestionbank_topic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_source_path', models.CharField(blank=True, help_text='Folder path where biometric Excel files are placed', max_length=500, null=True, verbose_name='Excel Source Path')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.AlterUniqueTogether(
            name='biometricattendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='biometricattendance',
            name='attendance_date',
            field=models.DateField(blank=True, null=True, verbose_name='Attendance Date'),
        ),
        migrations.AddField(
            model_name='biometricattendance',
            name='os',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Os'),
        ),
        migrations.AlterField(
            model_name='biometricattendance',
            name='card_no',
            field=models.CharField(max_length=50, verbose_name='Card No'),
        ),
        migrations.AlterField(
            model_name='biometricattendance',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='biometricattendance',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='biometricattendance',
            name='early_arrival',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Early Arriv.'),
        ),
        migrations.AlterField(
            model_name='biometricattendance',
            name='employee_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Employee Name'),
        ),
        migrations.AlterField(
            model_name='biometricattendance',
            name='excess_lunch',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Excess Lunch'),
        ),
        migrations.AlterField(
            model_name='biometricattendance',
            name='hrs_works',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Hrs Works'),
        ),
        migrations.AlterField(
            model_name='biometricattendance',
            name='in_time',
            field=models.TimeField(blank=True, null=True, verbose_name='In'),
        ),
        migrations.AlterField(
            model_name='biometricattendance',
            name='late_arrival',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Late Arriv.'),
        ),
        migrations.AlterField(
            model_name='biometricattendance',
            name='ot',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ot'),
        ),
        migrations.AlterField(
            model_name='biometricattendance',
            name='ot_amount',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ot Amount'),
        ),
        migrations.AlterField(
            model_name='biometricattendance',
            name='out_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Out'),
        ),
        migrations.AlterField(
            model_name='biometricattendance',
            name='pay_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PayCode'),
        ),
        migrations.AlterField(
            model_name='biometricattendance',
            name='shift',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Shift'),
        ),
        migrations.AlterField(
            model_name='biometricattendance',
            name='shift_early',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Shift Early'),
        ),
        migrations.AlterField(
            model_name='biometricattendance',
            name='sr_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sr.No.'),
        ),
        migrations.AlterField(
            model_name='biometricattendance',
            name='start',
            field=models.TimeField(blank=True, null=True, verbose_name='Start'),
        ),
        migrations.AlterField(
            model_name='biometricattendance',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterUniqueTogether(
            name='biometricattendance',
            unique_together={('card_no', 'attendance_date')},
        ),
    ]
