# Generated by Django 5.2.8 on 2025-12-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('app1', '0136_remove_refresherquestionbank_topic_and_more'),
        ('app1', '0136_actionitem_actionitemrejection'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='is_timer_enabled',
            field=models.BooleanField(default=True, help_text='Enable countdown timer for this paper'),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='question_duration',
            field=models.PositiveIntegerField(default=30, help_text='Time in seconds per question'),
        ),
        migrations.AlterModelTable(
            name='questionpaper',
            table='question_paper',
        ),
    ]
