# Generated by Django 5.2.8 on 2025-12-10 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0137_questionpaper_is_timer_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefresherBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employees', models.ManyToManyField(related_name='refresher_batches', to='app1.mastertable')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresher_batches', to='app1.schedule')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('schedule', 'batch_number')},
            },
        ),
    ]
