# Generated by Django 5.2.8 on 2025-12-10 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0138_refresherbatch'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='refreshertestsession',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='refreshertestsession',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_sessions', to='app1.refresherbatch'),
        ),
        migrations.AlterUniqueTogether(
            name='refreshertestsession',
            unique_together={('schedule', 'employee', 'test_type', 'batch')},
        ),
    ]
