# Generated by Django 5.2.8 on 2025-12-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0139_alter_refreshertestsession_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatequestion',
            name='correct_index',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='templatequestion',
            name='option_a_lang2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='templatequestion',
            name='option_b_lang2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='templatequestion',
            name='option_c_lang2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='templatequestion',
            name='option_d_lang2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='templatequestion',
            name='question_lang2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
