# Generated by Django 5.2.8 on 2025-12-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0140_templatequestion_correct_index_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='templatequestion',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='templatequestion',
            name='is_active',
            field=models.BooleanField(default=True, help_text='If false, this question is hidden from normal selection.'),
        ),
        migrations.AddField(
            model_name='templatequestion',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Display order of this question within its question paper.'),
        ),
        migrations.AlterModelTable(
            name='templatequestion',
            table='template_question',
        ),
    ]
