# Generated by Django 5.2.8 on 2025-12-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('app1', '0134_alter_templatequestion_options_and_more'),
        ('app1', '0141_alter_templatequestion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamToolFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tool_uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
