# Generated by Django 5.1 on 2025-12-12 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('app1', '0141_alter_templatequestion_options_and_more'),
        ('app1', '0142_examtoolfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiSkillingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('minimum_level', models.ForeignKey(help_text='Minimum skill level required for multiskilling eligibility', on_delete=django.db.models.deletion.CASCADE, to='app1.level')),
            ],
            options={
                'verbose_name': 'MultiSkilling Configuration',
                'verbose_name_plural': 'MultiSkilling Configurations',
            },
        ),
    ]
