# Generated by Django 5.1 on 2025-12-12 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0143_multiskillingconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiskillingconfig',
            name='minimum_level',
            field=models.ForeignKey(db_column='minimum_level_id', help_text='Minimum skill level required for multiskilling eligibility', on_delete=django.db.models.deletion.CASCADE, to='app1.level'),
        ),
    ]
