# Generated by Django 5.1 on 2025-12-16 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0144_alter_multiskillingconfig_minimum_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillTimeInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_interval_months', models.PositiveIntegerField(help_text='Time interval in months required to complete this skill')),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether time interval checking is enabled')),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, help_text='Department level - null means applies to all departments', null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.department')),
                ('line', models.ForeignKey(blank=True, help_text='Line level - null means applies to all lines', null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.line')),
                ('station', models.ForeignKey(help_text='Station/Skill for which interval is set', on_delete=django.db.models.deletion.CASCADE, to='app1.station')),
                ('subline', models.ForeignKey(blank=True, help_text='Subline level - null means applies to all sublines', null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.subline')),
            ],
            options={
                'verbose_name': 'Skill Time Interval',
                'verbose_name_plural': 'Skill Time Intervals',
                'unique_together': {('department', 'line', 'subline', 'station')},
            },
        ),
    ]
