# Generated by Django 5.1 on 2025-12-17 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0145_skilltimeinterval'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SkillTimeInterval',
        ),
    ]
