# Generated by Django 5.1 on 2025-12-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0146_delete_skilltimeinterval'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSkillTimeInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_interval_days', models.PositiveIntegerField(help_text='Time interval in days required before an employee can be assigned a new skill')),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether time interval checking is enabled globally')),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global Skill Time Interval',
                'verbose_name_plural': 'Global Skill Time Intervals',
            },
        ),
    ]
