# Generated by Django 5.1 on 2026-01-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0148_user_bio_user_created_at_user_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimationVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('video_file', models.FileField(upload_to='videos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
