# Generated by Django 5.2.8 on 2026-01-19 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0150_role_department_role_designation_user_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='department',
        ),
        migrations.RemoveField(
            model_name='role',
            name='designation',
        ),
    ]
