# Generated by Django 5.1 on 2026-01-31 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0151_remove_role_department_remove_role_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='section',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
