# Generated by Django 5.2.8 on 2026-06-30 07:16

import django.db.models.deletion
from django.db import migrations, models


def seed_rbac_defaults(apps, schema_editor):
    Role = apps.get_model('app1', 'Role')
    PermissionModule = apps.get_model('app1', 'PermissionModule')
    RoleModulePermission = apps.get_model('app1', 'RoleModulePermission')

    default_modules = [
        ('dashboard', 'Dashboard', 'Dashboards and summary widgets'),
        ('users', 'Users', 'User provisioning and account lifecycle'),
        ('roles', 'Roles', 'Role creation and permission governance'),
        ('courses', 'Courses', 'Course catalog and assignments'),
        ('groups', 'Groups', 'LMS groups and memberships'),
        ('reports', 'Reports', 'Operational and LMS reports'),
        ('notifications', 'Notifications', 'Alerts, inbox, and broadcasts'),
        ('planning', 'Planning', 'Training plans and schedules'),
        ('method', 'Method', 'Method settings and hierarchy management'),
        ('skill-matrix', 'Skill Matrix', 'Skill matrix setup and analytics'),
        ('assessments', 'Assessments', 'Tests, evaluations, and scoring'),
        ('ai-tools', 'AI Tools', 'AI-powered authoring and assistants'),
    ]

    modules_by_slug = {}
    for index, (slug, name, description) in enumerate(default_modules, start=1):
        module, _ = PermissionModule.objects.get_or_create(
            slug=slug,
            defaults={
                'name': name,
                'description': description,
                'sort_order': index,
                'is_active': True,
            },
        )
        modules_by_slug[slug] = module

    default_permissions = {
        'admin': {slug: ['can_view', 'can_create', 'can_update', 'can_delete', 'can_approve', 'can_export', 'can_manage'] for slug, _, _ in default_modules},
        'team-leader': {
            'dashboard': ['can_view'],
            'courses': ['can_view', 'can_create', 'can_update'],
            'groups': ['can_view', 'can_create', 'can_update'],
            'reports': ['can_view'],
            'notifications': ['can_view'],
            'planning': ['can_view'],
            'assessments': ['can_view', 'can_update'],
        },
        'employee': {
            'dashboard': ['can_view'],
            'courses': ['can_view'],
            'groups': ['can_view'],
            'reports': ['can_view'],
            'notifications': ['can_view'],
            'assessments': ['can_view'],
        },
    }

    for role_name, module_map in default_permissions.items():
        role = Role.objects.filter(name=role_name).first()
        if not role:
            continue

        for module_slug, enabled_fields in module_map.items():
            permission, _ = RoleModulePermission.objects.get_or_create(
                role=role,
                module=modules_by_slug[module_slug],
            )
            for field_name in ['can_view', 'can_create', 'can_update', 'can_delete', 'can_approve', 'can_export', 'can_manage']:
                setattr(permission, field_name, field_name in enabled_fields)
            permission.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0153_alter_user_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Permission Module',
                'verbose_name_plural': 'Permission Modules',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoleModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_update', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_approve', models.BooleanField(default=False)),
                ('can_export', models.BooleanField(default=False)),
                ('can_manage', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='app1.permissionmodule')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to='app1.role')),
            ],
            options={
                'verbose_name': 'Role Module Permission',
                'verbose_name_plural': 'Role Module Permissions',
                'ordering': ['module__sort_order', 'module__name'],
                'unique_together': {('role', 'module')},
            },
        ),
        migrations.RunPython(seed_rbac_defaults, migrations.RunPython.noop),
    ]
